// <auto-generated />
namespace GymBoyAttendance.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GymBoyAttendanceContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GymBoyAttendanceContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201411250105239_GymBoyAttendanceContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
